Repository canonical/wazuh-server-operator, pull requests merged in 2025-08, with the labels that each got.

#269 enhancement/cache-state
  src/charm.py
Labels: enhancement, trivial

#271 feat(docs): Evolve and standardize the documentation workflow
  .custom_wordlist.txt
  .github/workflows/docs.yaml
  .github/workflows/test.yaml
  .gitignore
  .vale.ini
  .vale/styles/config/vocabularies/local/accept.txt
  Makefile
  Makefile.docs
  README.md
  docs/changelog.md
  docs/explanation/charm-architecture.md
  docs/how-to/deploy-to-production.md
  docs/index.md
  docs/reference/integrations.md
Labels: documentation

#258 Fixed lint dependencies
  .github/workflows/test.yaml
  docs/changelog.md
  tox.ini
Labels: bug, trivial
