Repository canonical/wazuh-server-operator, pull requests merged in 2025-04, with the labels that each got.

#133 Feat/support local testing
  tests/conftest.py
  tests/integration/config_single_node_index.sh
  tests/integration/conftest.py
Labels: Libraries: Out of sync

#137 Explicit offer_url
  terraform/product/main.tf
  terraform/product/variables.tf
Labels: Libraries: Out of sync

#139 Add wazuh-api credentials relation
  charmcraft.yaml
  lib/charms/wazuh_server/v0/wazuh_api.py
  src/certificates_observer.py
  src/charm.py
  src/traefik_route_observer.py
  src/wazuh.py
  tests/integration/conftest.py
  tests/unit/test_library_wazuh_api.py
  tests/unit/test_traefik_route_observer.py
  tox.ini
Labels: senior-review-required

#140 Delete everything, including .git
  charmcraft.yaml
  src/wazuh.py
  tests/integration/conftest.py
  tests/unit/test_wazuh.py
Labels: Libraries: Out of sync

#141 Grant access to wazuh api secret
  src/charm.py
Labels: Libraries: Out of sync, trivial

#134 POC to use an external CA to authenticate the rsyslog clients
  .github/workflows/integration_test.yaml
  .licenserc.yaml
  charmcraft.yaml
  docs/how-to/collect-logs.md
  src/charm.py
  src/state.py
  tests/integration/certs/bad-client.crt
  tests/integration/certs/bad-client.csr
  tests/integration/certs/bad-client.key
  tests/integration/certs/ca.crt
  tests/integration/certs/ca.key
  tests/integration/certs/ca.srl
  tests/integration/certs/client.csr
  tests/integration/certs/good-client.crt
  tests/integration/certs/good-client.key
  tests/integration/config_single_node_index.sh
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/pre_run_script.sh
  tests/integration/test_charm.py
  tests/unit/test_certificates_observer.py
  tests/unit/test_charm.py
  tests/unit/test_state.py
Labels: Libraries: Out of sync

#145 Bootstrap security documentation
  docs/explanation/security.md
Labels: Libraries: Out of sync

#144 Increase timeout for cloning the configuration repository
  .github/workflows/integration_test.yaml
  src/wazuh.py
  tests/integration/conftest.py
  tests/unit/test_wazuh.py
Labels: Libraries: Out of sync, trivial

#143 Add support for the new relation to terraform
  terraform/charm/outputs.tf
  terraform/product/main.tf
  terraform/product/variables.tf
Labels: Libraries: Out of sync

#148 Remove collision with local credentials
  lib/charms/wazuh_server/v0/wazuh_api.py
Labels: Libraries: Out of sync

#146 Catch the invalid config earlier
  requirements-charmcraft.txt
  src/charm.py
  src/state.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/unit/test_certificates_observer.py
  tests/unit/test_charm.py
  tests/unit/test_state.py
Labels: Libraries: Out of sync

#150 Set wazuh api data on relation changed event
  src/charm.py
Labels: Libraries: Out of sync, trivial

#151 Update how to back up documentation
  docs/how-to/backup-restore.md
Labels: documentation, Libraries: Out of sync

#153 Support deploying the dashboard in a different model
  terraform/product/main.tf
  terraform/product/variables.tf
  terraform/product/versions.tf
Labels: Libraries: Out of sync

#154 Fix filebeat authentication
  .trivyignore
  rock/rockcraft.yaml
  terraform/product/variables.tf
Labels: bug, Libraries: Out of sync

#157 Fix dashboard plans
  terraform/product/main.tf
Labels: bug, Libraries: Out of sync

#159 Unpin indexer module
  terraform/product/main.tf
Labels: bug, Libraries: Out of sync

#160 Fix TF product access offer
  terraform/product/main.tf
Labels: bug, Libraries: Out of sync

#161 Fix TF modules offer accesses
  terraform/product/main.tf
Labels: bug, Libraries: Out of sync

#162 Delete configuration files if not present in the repository
  docs/how-to/configure.md
  src/wazuh.py
Labels: Libraries: Out of sync, senior-review-required

#164 Fix ossec configuration
  src/wazuh.py
Labels: bug, Libraries: Out of sync

#165 Fix relation data parsing in lib
  lib/charms/wazuh_server/v0/wazuh_api.py
Labels: bug, Libraries: Out of sync

#166 Make wazuh api lib support pydantic 1
  lib/charms/wazuh_server/v0/wazuh_api.py
Labels: bug, Libraries: Out of sync

#167 Add COS support for TF modules
  terraform/product/outputs.tf
Labels: Libraries: Out of sync, trivial

#168 Update indexer and dashboard TF modules
  terraform/charm/versions.tf
  terraform/product/main.tf
  terraform/product/modules/s3-integrator/versions.tf
  terraform/product/outputs.tf
  terraform/product/variables.tf
  terraform/product/versions.tf
Labels: Libraries: Out of sync
