Repository canonical/wazuh-server-operator, pull requests merged in 2025-06, with the labels that each got.

#190 Mount value to persist data across container restarts
  charmcraft.yaml
  docs/explanation/charm-architecture.md
  rock/wazuh.conf
  tests/integration/helpers.py
Labels: Libraries: Out of sync, trivial

#191 Add storage for collector logs
  rock/rockcraft.yaml
  rock/wazuh.conf
  src/charm.py
  src/wazuh.py
  tests/integration/helpers.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, trivial

#186 Wazuh integration with OpenCTI
  charmcraft.yaml
  docs/changelog.md
  src/charm.py
  src/opencti_connector_observer.py
  src/state.py
  src/wazuh.py
  tests/integration/any_charm.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/test_charm.py
  tests/unit/test_opencti_observer.py
  tests/unit/test_state.py
  tox.ini
Labels: Libraries: Out of sync

#193 Ignore changelog from codeowner requests
  CODEOWNERS
Labels: Libraries: Out of sync, trivial

#198 Add OpenCTI integration documentation
  docs/changelog.md
  docs/how-to/configure.md
  docs/how-to/integrate-with-opencti.md
Labels: documentation, Libraries: OK, trivial

#201 Modify `rsync` command
  .trivyignore
  CODEOWNERS
  docs/changelog.md
  src/wazuh.py
Labels: bug, Libraries: OK, trivial

#203 Change ownership of files during rsync
  docs/changelog.md
  src/wazuh.py
Labels: bug, Libraries: OK, trivial

#208 Split architecture diagrams
  docs/changelog.md
  docs/explanation/architecture-overview.md
  docs/explanation/charm-architecture.md
Labels: documentation, Libraries: OK

#212 Change exception to blocked status for missing OpenCTI integration
  docs/changelog.md
  src/charm.py
  src/wazuh.py
Labels: bug, Libraries: Out of sync, trivial

#218 Update dependency
  terraform/product/main.tf
Labels: Libraries: Out of sync

#219 Add how to redeploy documentation
  docs/changelog.md
  docs/how-to/redeploy.md
  docs/index.md
Labels: documentation, Libraries: Out of sync

#217 Move the charm status setting logic to the reconcile loop
  docs/changelog.md
  src/charm.py
  tests/unit/test_charm.py
Labels: bug, Libraries: OK, trivial
