Repository canonical/wazuh-server-operator, pull requests merged in 2025-07, with the labels that each got.

#225 Add relation departed hooks
  docs/changelog.md
  src/charm.py
  src/opencti_connector_observer.py
  src/opensearch_observer.py
Labels: bug, Libraries: Out of sync, trivial

#227 Set dry run to false to publish documentation
  .github/workflows/promote_charm.yaml
Labels: Libraries: OK, trivial

#232 update documentation link and icon
  .licenserc.yaml
  charmcraft.yaml
  icon.png
  icon.svg
Labels: Libraries: OK, trivial

#238 Update link to setup Canonical Kubernetes
  CONTRIBUTING.md
Labels: Libraries: OK, trivial

#231 Upgrade prometheus exporter
  .github/workflows/integration_test.yaml
  docs/changelog.md
  requirements-charmcraft.txt
  rock/rockcraft.yaml
  src/charm.py
  tests/integration/conftest.py
Labels: Libraries: OK

#223 Doc/testing
  docs/how-to/test-your-deployment.md
Labels: documentation, Libraries: OK

#244 Do not debug on integration test failure
  .github/workflows/integration_test.yaml
Labels: trivial
