Repository canonical/wazuh-server-operator, pull requests merged in 2025-03, with the labels that each got.

#90 Tls termination
  docs/explanation/charm-architecture.md
  src/traefik_route_observer.py
  src/wazuh.py
  tests/integration/helpers.py
  tests/integration/test_charm.py
  tests/unit/test_traefik_route_observer.py
  tox.ini
Labels: Libraries: Out of sync, trivial

#91 Install rsyslog server
  .licenserc.yaml
  rock/rockcraft.yaml
  rock/wazuh.conf
  src/certificates_observer.py
  src/charm.py
  src/state.py
  src/traefik_route_observer.py
  src/wazuh.py
  tests/integration/test_charm.py
  tests/unit/resources/ossec.conf
  tests/unit/test_certificates_observer.py
  tests/unit/test_charm.py
  tests/unit/test_state.py
  tests/unit/test_traefik_route_observer.py
  tests/unit/test_wazuh.py
Labels: Libraries: Out of sync

#94 Retrieve external hostname from relation data
  src/certificates_observer.py
  src/charm.py
  src/state.py
  tests/unit/test_certificates_observer.py
  tests/unit/test_charm.py
  tests/unit/test_state.py
Labels: bug, Libraries: Out of sync, senior-review-required

#95 Simplify TLS certificates management
  src/certificates_observer.py
  src/charm.py
  src/state.py
  tests/unit/test_certificates_observer.py
  tests/unit/test_charm.py
  tests/unit/test_state.py
Labels: Libraries: Out of sync, trivial

#96 Add additional debug logs
  src/state.py
Labels: Libraries: Out of sync, trivial

#97 add white line at the end of the key file
  src/wazuh.py
Labels: trivial

#100 Enable mutual TLS
  rock/wazuh.conf
Labels: trivial

#102 Fix syslog group creation
  rock/rockcraft.yaml
  src/charm.py
Labels: Libraries: Out of sync, trivial

#103 Fix filebeat execution
  .trivyignore
  rock/rockcraft.yaml
  src/charm.py
  src/wazuh.py
Labels: Libraries: Out of sync, trivial

#106 Do not reload the wazuh service when reconciling
  src/charm.py
  src/wazuh.py
  tests/unit/test_charm.py
  tests/unit/test_wazuh.py
Labels: Libraries: Out of sync, trivial

#104 Improve charm stability
  src/certificates_observer.py
  src/charm.py
  src/state.py
  src/wazuh.py
  tests/unit/test_state.py
Labels: Libraries: Out of sync, trivial

#107 Tune cmd timeouts
  src/wazuh.py
Labels: bug, Libraries: Out of sync, trivial

#108 Improve integration test stability
  src/charm.py
  src/state.py
  tests/integration/conftest.py
Labels: Libraries: Out of sync

#109 Fix readiness pebble check for wazuh
  src/charm.py
Labels: Libraries: Out of sync

#111 Fix syslog configuration
  src/charm.py
  src/wazuh.py
  tests/unit/test_charm.py
Labels: bug, Libraries: Out of sync

#113 Fix file permissions for rsyslog
  rock/rockcraft.yaml
  src/charm.py
  src/wazuh.py
  tests/unit/test_charm.py
  tests/unit/test_wazuh.py
Labels: Libraries: Out of sync, trivial

#114 Change rsync log path
  rock/rockcraft.yaml
  rock/wazuh.conf
Labels: Libraries: Out of sync, trivial

#115 Change syslog file location
  rock/rockcraft.yaml
  rock/wazuh.conf
Labels: Libraries: Out of sync, trivial

#116 Increase timeouts
  src/wazuh.py
Labels: Libraries: Out of sync, trivial

#120 Remove additional filebeat package
  rock/rockcraft.yaml
  src/wazuh.py
Labels: trivial

#122 Fix filebeat executable
  rock/rockcraft.yaml
Labels: bug, Libraries: Out of sync

#123 Assign project to EMEA A
  CODEOWNERS
Labels: Libraries: Out of sync

#101 Added changelog
  .github/pull_request_template.yaml
  CHANGELOG.md
  docs/changelog.md
Labels: Libraries: Out of sync, trivial

#124 Add charm module and product terraform plans
  terraform/.gitignore
  terraform/charm/README.md
  terraform/charm/main.tf
  terraform/charm/outputs.tf
  terraform/charm/variables.tf
  terraform/charm/versions.tf
  terraform/product/README.md
  terraform/product/main.tf
  terraform/product/outputs.tf
  terraform/product/variables.tf
  terraform/product/versions.tf
Labels: Libraries: Out of sync, senior-review-required

#129 Doc/howto upgrade
  docs/how-to/upgrade.md
Labels: Libraries: Out of sync

#131 Describe how to configure the system to collect logs
  docs/how-to/collect-logs.md
Labels: Libraries: Out of sync

#125 Enrich documentation
  docs/explanation/architecture-overview.md
  docs/explanation/charm-architecture.md
  docs/how-to/backup-restore.md
  docs/how-to/deploy-to-production.md
  docs/tutorial/getting-started.md
Labels: Libraries: Out of sync

#135 Change TF default bases
  docs/how-to/deploy-to-production.md
  terraform/charm/variables.tf
  terraform/product/variables.tf
Labels: Libraries: Out of sync, trivial
